main: io.th0rgal.oraxen.OraxenPlugin
name: Oraxen
version: ${projectVersion}
author: Th0rgal
api-version: "1.14"
softdepend: [ProtocolLib, MythicMobs, CrateReloaded, BossShopPro, ItemBridge]
loadbefore: [Realistic_World]
